version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: shop-dev-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shop_dev_db
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--skip-character-set-client-handshake'
    ]
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - shop-dev-network

  redis:
    image: redis:latest
    container_name: shop-dev-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - shop-dev-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: shop-dev-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - shop-dev-network

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: shop-dev-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - shop-dev-network

networks:
  shop-dev-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data: