spring:
  application:
    name: shop-dev-be
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: shop-dev-be-pool
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          server-time-zone: Asia/Ho_Chi_Minh
  
  security:
    oauth2:
      client:
        registration:
          google:
            scope:
            - email
            - profile
            - openid

  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: false

  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted-packages: com.shintadev.shop_dev_be.domain.dto

server:
  port: 8080
  servlet:
    context-path: /api
  compression:
    enabled: true

